usr/lib/kde4/plasma_applet_knewsticker.so
usr/share/kde4/services/plasma-knewsticker-default.desktop
usr/share/icons/hicolor/32x32/apps/knewsticker.png
usr/share/icons/hicolor/16x16/apps/knewsticker.png
usr/share/icons/hicolor/48x48/apps/knewsticker.png

usr/share/doc/kde4/HTML/en/knewsticker/index.cache.bz2
usr/share/doc/kde4/HTML/en/knewsticker/index.docbook
usr/share/doc/kde4/HTML/en/knewsticker/knewsticker-ownwindow.png
usr/share/doc/kde4/HTML/en/knewsticker/knewsticker-kicker.png
usr/share/doc/kde4/HTML/en/knewsticker/knewsticker-childpanel.png
usr/share/doc/kde4/HTML/en/knewsticker/knewsticker-icon.png
usr/share/doc/kde4/HTML/en/knewsticker/kcmnewsticker-filters.png
usr/share/doc/kde4/HTML/en/knewsticker/checknews-icon.png
usr/share/doc/kde4/HTML/en/knewsticker/kcmnewsticker-scrollerprefs.png
usr/share/doc/kde4/HTML/en/knewsticker/oldarticle-icon.png
usr/share/doc/kde4/HTML/en/knewsticker/newarticle-icon.png
usr/share/doc/kde4/HTML/en/knewsticker/preferences-icon.png
usr/share/doc/kde4/HTML/en/knewsticker/about-icon.png
usr/share/doc/kde4/HTML/en/knewsticker/kcmnewsticker-newssources.png
usr/share/doc/kde4/HTML/en/knewsticker/help-icon.png
usr/share/doc/kde4/HTML/en/knewsticker/contextmenu.png
usr/share/doc/kde4/HTML/en/knewsticker/kcmnewsticker-general.png
usr/share/doc/kde4/HTML/en/knewsticker/newssite-icon.png
usr/share/doc/kde4/HTML/en/knewsticker/kcontrol-icon.png
usr/share/doc/kde4/HTML/en/knewsticker/kcmnewsticker-newssitedialog.png

