usr/bin/krdc
usr/share/kde4/apps/krdc/krdcui.rc
usr/share/applications/kde4/krdc.desktop
usr/share/kde4/services/vnc.protocol
usr/share/kde4/services/rdp.protocol
usr/share/kde4/apps/zeroconf/_rfb._tcp
usr/share/kde4/apps/krdc/pics/pointcursor.png
usr/share/kde4/apps/krdc/pics/pointcursormask.png
usr/share/kde4/config.kcfg/krdc.kcfg

usr/share/doc/kde4/HTML/en/krdc/index.cache.bz2
usr/share/doc/kde4/HTML/en/krdc/index.docbook
usr/share/doc/kde4/HTML/en/krdc/vnc_preferences.png
usr/share/doc/kde4/HTML/en/krdc/vnc_host_configuration.png
usr/share/doc/kde4/HTML/en/krdc/address_input.png
usr/share/doc/kde4/HTML/en/krdc/bookmarks_menu.png
usr/share/doc/kde4/HTML/en/krdc/host_preferences.png
usr/share/doc/kde4/HTML/en/krdc/krdc_mainwindow.png
usr/share/doc/kde4/HTML/en/krdc/fullscreen_button.png
usr/share/doc/kde4/HTML/en/krdc/rdp_preferences.png
usr/share/doc/kde4/HTML/en/krdc/password_entry.png
usr/share/doc/kde4/HTML/en/krdc/windowmode_button.png

